#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "${DIR}/../lib/plugin.bash"

REPOSITORY_URL_OPTION=$(plugin_read_config REPOSITORY_URL "${BUILDKITE_REPO:-}")
SSH_SECRET_KEY_NAME_OPTION=$(plugin_read_config SSH_SECRET_KEY_NAME "GIT_SSH_CHECKOUT_PLUGIN_SSH_KEY")
CHECKOUT_PATH_OPTION=$(plugin_read_config CHECKOUT_PATH "./")

echo "Running SSH Checkout plugin with options:"
echo " - repository-url: ${REPOSITORY_URL_OPTION} vs. ${BUILDKITE_REPO:-}"
echo " - ssh-secret-key-name: ${SSH_SECRET_KEY_NAME_OPTION} vs. ${BUILDKITE_GIT_CLONE_FLAGS:-}"
echo " - checkout-path: ${CHECKOUT_PATH_OPTION} vs. ${BUILDKITE_BUILD_CHECKOUT_PATH:-}"
