#!/bin/bash

echo "Running pre-checkout hook from my-plugin..."
ls -la ~/.ssh
cat $(buildkite-agent secret get BITBUCKET_SSH_UCLOUD)
printf "%s\n" "$(buildkite-agent secret get BITBUCKET_SSH_UCLOUD)"
